# Generated by Django 5.2.6 on 2025-10-28 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorelog',
            options={'ordering': ['-score']},
        ),
    ]
